apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Production namespace
namespace: expresscart

resources:
- ../../../base

images:
  - name: repo.lab/expresscart
    newTag: 1.0.2

patches:
- path: ingress-production.yaml

